#!/bin/bash

########################  REQUIRED

_echot "------- required files"
file_env=${S_PATH_SCRIPT}/conf/.sh_env
file_sh_aliases=${S_PATH_SCRIPT}/conf/.sh_aliases
file_sh_functions=${S_PATH_SCRIPT}/conf/.sh_functions
file_env_perso=${_PATH_BASE}/conf/.sh_env_perso
_require ${file_env} ${file_sh_aliases} ${file_sh_functions} ${file_env_perso}

_echot "------- required paths"
pth_shared_bs=/home/shared/repo/bs

########################  SYSTEM

_echot "------- iommu"
 file=/etc/default/grub
_askyn "Add 'iommu=soft' in GRUB_CMDLINE_LINUX variable ?"
[ "${_ANSWER}" = y ] && sudo sed -i '/^GRUB_CMDLINE_LINUX="/ s|"$| iommu=soft"|' ${file}
_confset _SYSNAME "${_SYSNAME}"

_echot "------- create paths"
pths="ext/backup ext/ovh ext/shared /home/shared"
for pth in ${pths}; do
	[ -d "${pth}" ] || _evalr mkdir -p ${pth}
	_evalr chown ${USER}:${USER} ${pth}
done

file=/etc/fstab
if [ -d ${pth_shared_bs} ] && ! grep -q "${S_PATH_SCRIPT}" ${file}; then
	_echot "------- path ${S_PATH_SCRIPT}"
	[ -d "${S_PATH_SCRIPT}" ] && _evalr rm -fR "${S_PATH_SCRIPT}"
	[ -d "${S_PATH_SCRIPT}" ] || _evalr mkdir -p "${S_PATH_SCRIPT}"
	_echot "------- ${file} ${S_PATH_SCRIPT}"
	sudo sh -c "echo '
# bind ${S_PATH_SCRIPT}
${pth_shared_bs}				${S_PATH_SCRIPT}	none	defaults,bind										0 0' >> ${file}"
	_echot "------- daemon-reload"
	_evalr systemctl daemon-reload
	_echot "------- bind ${S_PATH_SCRIPT}"
	_evalr mount ${S_PATH_SCRIPT}
	[ -d ${S_PATH_SCRIPT} ] || _exite "Unable to mount path: '${S_PATH_SCRIPT}'"
else
	_echoE "------- binding ${S_PATH_SCRIPT} to ${pth_shared_bs} is skipping"
fi

_echot "------- reduce swappiness"
_evalr swapoff -av
sudo sh -c 'echo vm.swappiness=20 > /etc/sysctl.d/99-swappiness.conf' # limit swap
_evalr swapon -v

########################  USER

_echot "------- .sh_env"
file=${HOME}/.sh_env
_keepmvts ${file}
_eval ln -s ${file_env} ${file}

_echot "------- .sh_aliases"
file=~/.sh_aliases
_keepmvts ${file}
_eval ln -s ${file_sh_aliases} ${file}

_echot "------- .sh_functions"
file=~/.sh_functions
_keepmvts ${file}
_eval ln -s ${file_sh_functions} ${file}

_echot "------- .sh_env_perso"
file=${HOME}/.sh_env_perso
_keepmvts ${file}
_eval cp -a ${file_env_perso} ${file}

for file in ~/.bashrc ~/.zshrc; do
	_echot "------- ${file##*/} env_perso"
	grep -q ".sh_env_perso" ${file} || echo "
# sh_env_perso
[ -f \${HOME}/.sh_env_perso ] && . \${HOME}/.sh_env_perso" >> ${file}
done

_echot "------- .zshrc"
echo "
########################  SET OPTIONS

# split words in string with default delimiters ' '
setopt shwordsplit
# allows interactive comments in console
setopt interactivecomments
" >> ~/.zshrc

_echot "------- user links"
for file in .nanorc .tmux.conf .vimrc; do
	pth=${HOME}/${file}
	_keepmvts "${pth}"
	_eval ln -s "${S_PATH_SCRIPT}/conf/${file}" "${pth}"
done

_echot "------- gtk bookmarks"
file=~/.config/gtk-3.0/bookmarks
echo "file:///home
file:///ext
file:///home/shared/dev
file:///home/shared/repo" >> ${file}
