#!/bin/bash

########################  DATA

_PATH_SOFT=/ext/shared/Soft/linux
_PATH_SOFT_BACKUP=/ext/shared/Soft/linux/backup

_menu "Select a theme for eclipse" java tools
_ECLIPSE_THEME=${_ANSWER}

anstmp=${_PATH_SOFT_BACKUP}
_askno "Give the software backup path to restore from ? ${anstmp}"
_PATH_SOFT_BACKUP=${_ANSWER:-${anstmp}}

_menu "Select the date to restore eclipse or none" none `ls -1r ${_PATH_SOFT_BACKUP}|sed -n "s|^eclipse_${_ECLIPSE_THEME}_\([0-9-]\+\)\.tar\.gz$|\1|p"`
_ECLIPSE_DATE=${_ANSWER/none/}

if [ -z ${_ECLIPSE_DATE} ]; then
	anstmp="2025-12"
	_askno "Give Eclipse version to install or none? ${anstmp}"
	_ECLIPSE_VER=${_ANSWER:-${anstmp}}
fi

pth_opt=/opt/eclipse_${_ECLIPSE_THEME}
pth_conf=.eclipse_${_ECLIPSE_THEME}
pth_proj=${HOME}/dev/eclipse-workspaces-${_ECLIPSE_THEME}
pth_desk=~/.local/share/applications
file_desk=${pth_desk}/eclipse_java.desktop
file_bin=/usr/local/bin/eclipse_${_ECLIPSE_THEME}

########################  REQUIRED

file_desk_xtra=${_PATH_BASE}/xtra/eclipse_${_ECLIPSE_THEME}.desktop

_require ${file_desk_xtra}

########################  BACKUP

if [ -d "${pth_opt}" ] || [ -d ~/${pth_conf} ] || [ -d "${pth_proj}" ]; then
	if ! [ -d ${_PATH_SOFT_BACKUP} ]; then
		_evalr mkdir -p ${_PATH_SOFT_BACKUP}
		_evalr chown ${USER}:${USER} ${_PATH_SOFT_BACKUP}
	fi

	file=${_PATH_SOFT_BACKUP}/eclipse_${_ECLIPSE_THEME}_backup_${_DATE}-$(date +%s).tar.gz
	pths=
	_echot "------- backup to "
	for pth in ${pth_opt} ~/${pth_conf} ${pth_proj} ${file_desk} ${file_bin}; do
		[ -e ${pth} ] && pths+=" ${pth}"
	done
	tar czf ${file} ${pths}
fi

_echot "------- clean instance"
# delete existing folder
for pth in ${pth_opt} ~/${pth_conf} ${pth_proj} ${file_desk} ${file_bin}; do
	[[ -e ${pth} || -h ${pth} ]] && _evalr rm -fR ${pth}
done

####################  RESTORE

if [ "${_ECLIPSE_DATE}" ]; then

	[ -h ~/dev ] || ln -s /home/shared/dev ~/dev
	backup-soft --restore ${_ECLIPSE_DATE} eclipse_${_ECLIPSE_THEME} --force

####################  FRESH INSTALL

else [ "${_ECLIPSE_VER}" ]

	anstmp=${_PATH_SOFT}
	_askno "Give the software path to save ? ${anstmp}"
	_PATH_SOFT=${_ANSWER:-${anstmp}}

	_echot "------- create path"
	for pth in ~/${pth_conf} ${pth_proj}; do
		[ -d ${pth} ] || _evalr mkdir -p ${pth}
		_evalr chown 1000:1000 ${pth}
	done

	cd /tmp
	_echot "------- get"
	file=eclipse-java-${_ECLIPSE_VER}-R-linux-gtk-x86_64.tar.gz
	url=http://mirror.ibcp.fr/pub/eclipse//technology/epp/downloads/release/${_ECLIPSE_VER}/R/${file}
	if [ -f "${_PATH_SOFT}/${file}" ]; then
		_eval cp ${_PATH_SOFT}/${file} .
	else
		_ANSWER=${file}
		_echot "------- download"
		while ! _eval wget -q "${url}" -O "${_ANSWER}"; do
			_ask "Unable to donwload:\n${url}\nGive a good url to download ${file}\nConfirm"
		done
		if ! [ -d "${_PATH_SOFT}" ]; then
			_evalr mkdir -p ${_PATH_SOFT}
			_evalr chown ${USER}:${USER} ${_PATH_SOFT}
		fi
		_evalr cp ${file} ${_PATH_SOFT}/
	fi

	_echot "------- install"
	[ -d eclipse ] && _evalr rm -fR eclipse
	_eval tar xzf ${file}
	_evalr mv eclipse ${pth_opt}
	_eval rm ${file}

	_echot "------- ${file_bin} bind"
	sudo [ -e "${file_bin}" ] && _evalr rm ${file_bin}
	_evalr ln -s ${pth_opt}/eclipse ${file_bin}

	_echot "------- launcher"
	_eval cp ${file_desk_xtra} ${file_desk}
	_eval chmod +x ${file_desk}

fi

####################  COMMON

_echot "------- conf"
file=${pth_opt}/eclipse.ini
_keepcpts ${file}
grep -q '^-Duser' ${file} || sed -i "/^-vmargs/ a-Duser.home=${HOME}/.eclipse_${_ECLIPSE_THEME}" ${file}
sed -i "/^-Dosgi.instance.area.default/ s|=.*|=${pth_proj}/init|" ${file}
#sed -i "/^-Dosgi.instance.area.default/ s|=.*|=${pth_proj}/eclipse-workspaces-${_ECLIPSE_THEME}|" ${file}

_echot "------- jdk src doc"
_install_pcks openjdk-26-source openjdk-26-doc

<<KEEP
####  marketplace

https://marketplace.eclipse.org/content/bash-editor
https://marketplace.eclipse.org/content/jenkins-editor

http://www.eclipsecolorthemes.org


####  dev

# pydev
http://pydev.org/updates
# basheditor
https://dl.bintray.com/de-jcup/basheditor
# devstyle
http://www.genuitec.com/updates/devstyle/ci
# quickrex
http://netceteragroup.github.io/quickrex/updatesite
# dev-utils
http://kangtae49.github.io/dev-utils-plugin/update


####  modeling

# remove
gradle
EclEmma
Java development tools
justJ
m2e maven
POM
TM terminal
WWW

####  add
efxclipse
GEF dot

# color theme
http://eclipse-color-theme.github.io/update/

# dbeaver
https://dbeaver.io/update/latest/

# Papyrus
https://download.eclipse.org/modeling/mdt/papyrus/updates/releases/2021-09
https://download.eclipse.org/modeling/mdt/papyrus/updates/nightly/master
# SysML16
https://download.eclipse.org/modeling/mdt/papyrus/components/sysml16/2021-09
# Papyrus Software designer
http://download.eclipse.org/modeling/mdt/papyrus/components/designer/2.0.0


##### others

# Apache Directory Studio
http://directory.apache.org/studio/update/2.x

# Polarion
http://www.polarion.com/products/svn/subversive/download.php
## SVN connectors polarion
http://community.polarion.com/projects/subversive/download/eclipse/4.0/update-site/
http://community.polarion.com/projects/subversive/download/eclipse/4.0/luna-site/
## SVN Plugins integration
http://community.polarion.com/projects/subversive/download/integrations/luna-site/
http://download.eclipse.org/technology/subversive/2.0/update-site/

# SQLexplorer
http://eclipsesql.sourceforge.net/

# RSE (ftp)
http://download.eclipse.org/dsdp/tm/updates/3.0/

# Bastian-Bergerhoff
http://www.bastian-bergerhoff.com/eclipse/features

# Esftp
http://sourceforge.net/projects/esftp/

# connectors
    * DB2
          o Driver Class: COM.ibm.db2.jdbc.app.DB2Driver
          o Connection URL: jdbc:db2:
          o Driver .jar/.zip: db2java.zip
    * Sybase
          o Driver Class: com.sybase.jdbc2.jdbc.SybDriver
          o Connection URL: jdbc:sybase:Tds::/
          o Driver .jar/.zip: jconn2.jar
    * Oracle
          o Driver Class: oracle.jdbc.driver.OracleDriver
          o Connection URL: jdbc:oracle:thin:@ ::
          o Driver .jar/.zip: classes12.zip
    * SQLServer
          o Driver Class: com.microsoft.jdbc.sqlserver.SQLServerDriver
          o Connection URL: jdbc:microsoft:sqlserver://localhost:1433
          o Driver .jar/.zip: mssqlserver.jar, msbase.jar, msutil.jar
    * PostgreSQL
          o Driver Class: org.postgresql.Driver
          o Connection URL: jdbc:postgresql://
KEEP
