#!/bin/bash

_echot "------- git config"
git config --global user.name "aguy tech"
git config --global user.email aguytech@free.fr
git config --global core.editor vim
git config --global merge.tool meld

file=${HOME}/.gitconfig
grep -q '^[alias]' ${file} || echo -e "
[alias]
\tbr = branch
\tci = commit
\tco = checkout
\tdi = diff
\tst = status" >> ${file}

