#!/bin/bash

_echot "------- gnome-shell-extensions"
packages="gnome-shell-extension-manager"
_install_pcks ${packages}

_echot "------- extensions"
_echoA "Choose extensions to install like:"
_echoA "  Dash to Dock"
_echoA "  User Themes"
_echoA "  Vitals"
_askno "Validate to choose"
extension-manager
