#!/bin/bash

# xprop WM_CLASS
########################  MAIN

pth=~/.local/share/applications
[ -d "${pth}" ] || mkdir -p ${pth}

_echot "------- nautilus"
name=org.gnome.Nautilus
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="NautilusNode1;NautilusComputer;NautilusNetwork;Separator;Terminal;SshcDev;Sshc;SshcLxd"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action NautilusNode1]
Name=Nautilus node1
Exec=nautilus --new-window sftp://root@node1/usr/local/bs

[Desktop Action NautilusComputer]
Name=Nautilus Computer
Exec=nautilus --new-window computer:///

[Desktop Action NautilusNetwork]
Name=Nautilus Network
Exec=nautilus --new-window network:///

[Desktop Action Terminal]
Name=Terminal
Exec=gnome-terminal

[Desktop Action SshcDev]
Name=sshc dev
Exec=gnome-terminal --tab --tab-with-profile node1

[Desktop Action Sshc]
Name=sshc
Exec=gnome-terminal -e ssh-server

[Desktop Action SshcLxd]
Name=sshca
Exec=gnome-terminal -e /home/shared/repo/bs/ssh-lxd
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- org.gnome.Terminal"
name=org.gnome.Terminal
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd=";Separator;SshcDev;Sshc;SshcLxd;Separator;Nautilus;NautilusComputer;NautilusNetwork;"
			grep -q '^Actions=' ${pth}/${name}.desktop \
				&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
				|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Sshc]
Name=sshc
Exec=gnome-terminal -e ssh-server

[Desktop Action SshcDev]
Name=sshc dev
Exec=gnome-terminal --tab --tab-with-profile node1

[Desktop Action SshcLxd]
Name=sshca
Exec=gnome-terminal -e /home/shared/repo/bs/ssh-lxd

[Desktop Action Nautilus]
Name=Nautilus
Exec=nautilus --new-window

[Desktop Action NautilusComputer]
Name=Nautilus Computer
Exec=nautilus --new-window computer:///

[Desktop Action NautilusNetwork]
Name=Nautilus Network
Exec=nautilus --new-window network:///
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- org.gnome.Totem"
name=org.gnome.Totem
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;HandBrake;Brasero;MKVtoolnix;GnomeSubtitles;KDEnlive;Separator;Mpv;"
		sed -i "s/^\(Actions=.*\)$/\1${menuadd}/" ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Brasero]
Name=Brasero
Exec=brasero

[Desktop Action MKVtoolnix]
Name=MKVtoolnix GUI
Exec=mkvtoolnix-gui

[Desktop Action GnomeSubtitles]
Name=Gnome Subtitles
Exec=gnome-subtitles

[Desktop Action KDEnlive]
Name=KDEnlive Video Editor
Exec=kdenlive

[Desktop Action HandBrake]
Name=HandBrake
Exec=ghb

[Desktop Action Mpv]
Name=Mpv media player
Exec=mpv --player-operation-mode=pseudo-gui
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- mpv"
name=mpv
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		echo "Actions=Separator;HandBrake;Brasero;MKVtoolnix;GnomeSubtitles;KDEnlive;Separator;Totem;

[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Brasero]
Name=Brasero
Exec=brasero

[Desktop Action MKVtoolnix]
Name=MKVtoolnix GUI
Exec=mkvtoolnix-gui

[Desktop Action GnomeSubtitles]
Name=Gnome Subtitles
Exec=gnome-subtitles

[Desktop Action KDEnlive]
Name=KDEnlive Video Editor
Exec=kdenlive

[Desktop Action HandBrake]
Name=HandBrake
Exec=ghb

[Desktop Action Totem]
Name=Totem media player
Exec=totem
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- gmusicbrowser"
name=gmusicbrowser
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;Lollypop;PulseaudioEqualizer;Separator;Audacity;Easytag;SoundJuicer;SoundConverter;"
		sed -i "s/^\(Actions=.*\)$/\1${menuadd}/" ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Audacity]
Name=Audacity
Exec=audacity

[Desktop Action Easytag]
Name=Easytag
Exec=easytag %F

[Desktop Action Mixxx]
Name=Mixxx
Exec=mixxx

[Desktop Action SoundJuicer]
Name=SoundJuicer
Exec=sound-juicer

[Desktop Action SoundConverter]
Name=Sound Converter
Exec=soundconverter %U

[Desktop Action PulseaudioEqualizer]
Name=Pulseaudio Equalizer
Exec=qpaeq
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- gimp"
name=gimp
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		echo "Actions=gThumb;Inkscape;Separator;SimpleScan;XSane;

[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action gThumb]
Name=gThumb
Exec=gthumb %U

[Desktop Action Inkscape]
Name=Inkscape
Exec=inkscape %F

[Desktop Action SimpleScan]
Name=Simple Scan
Exec=simple-scan

[Desktop Action XSane]
Name=XSane Image scanning program
Exec=xsane
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- libreoffice-startcenter"
name=libreoffice-startcenter
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;Gcolor3;Calculator;Stopwatch;Activity;"
		sed -i "s/^\(Actions=.*\)$/\1${menuadd}/" ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Activity]
Name=Activity journal
Exec=gnome-activity-journal

[Desktop Action Calculator]
Name=Calculator
Exec=gnome-calculator

[Desktop Action Stopwatch]
Name=Stopwatch
Exec=/usr/bin/stopwatch

[Desktop Action Gcolor3]
Name=Color Picker
Exec=gcolor3
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- gnome-tweak-tool"
name=org.gnome.tweaks
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		echo "Actions=Separator;SoftwareUpdates;SoftwareSources;Separator;Gparted;DiskUtility;DiskUsage;Sysinfo;Separator;

[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action SoftwareUpdates]
Name=Update Manager
Exec=update-manager

[Desktop Action Synaptic]
Name=Synaptic
Exec=synaptic

[Desktop Action SoftwareSources]
Name=Software Sources
Exec=software-properties-gtk

[Desktop Action DiskUsage]
Name=Disk Usage
Exec=baobab

[Desktop Action DiskUtility]
Name=Disk Utility
Exec=gnome-disks

[Desktop Action Gparted]
Name=Gparted
Exec=gksudo gparted

[Desktop Action Sysinfo]
Name=Sysinfo
Exec=sysinfo
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi
