#!/bin/bash

# xprop WM_CLASS
########################  MAIN

pth=~/.local/share/applications
[ -d "${pth}" ] || mkdir -p ${pth}

_echot "------- xfce-settings-manager"
name=xfce-settings-manager
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;ManjaroSettings;XfceSettings;LightdmGtk;Qt6ct;DconfSet;PlankSet;Separator;PamacManager;TaskManager;Gparted;DiskUsage;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action PamacManager]
Name=Pamac Manager
Exec=pamac-manager

[Desktop Action XfceSettings]
Name=xfce4 settings
Exec=xfce4-settings-editor

[Desktop Action TaskManager]
Name=Task manager
Exec=xfce4-taskmanager

[Desktop Action LightdmGtk]
Name=lightdm Gtk greeter settings
Exec=lightdm-gtk-greeter-settings-pkexec

[Desktop Action Qt6ct]
Name=QT6 settings
Exec=qt6ct

[Desktop Action DiskUsage]
Name=Disk Usage
Exec=baobab

[Desktop Action Gparted]
Name=Gparted
Exec=gksudo gparted

[Desktop Action DconfSet]
Name=Dconf settings
Exec=dconf-editor

[Desktop Action ManjaroSettings]
Name=Manjaro settings
Exec=manjaro-settings-manager
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- thunar"
name=thunar
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="ThunarNode1;Separator;Terminal;SshDev;SshS;SshNode1;SshLxd;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action ThunarNode1]
Name=Thunar node1
Exec=thunar_newtabs /usr/local/bs sftp://root@node1/

[Desktop Action Terminal]
Name=Terminal
Exec=xfce4-terminal

[Desktop Action SshDev]
Name=ssh dev
Exec=xfce4-terminal --tab --tab --title=node1 -x ssh-server node1

[Desktop Action SshS]
Name=ssh server
Exec=xfce4-terminal --title=server -x ssh-server

[Desktop Action SshNode1]
Name=ssh node1
Exec=xfce4-terminal --tab --title=node1 -x ssh-server node1

[Desktop Action SshLxd]
Name=ssh LXD
Exec=xfce4-terminal --tab --title=LXD -x ssh-lxd
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- xfce4-terminal"
name=xfce4-terminal
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;SshDev;SshS;SshNode1;SshLxd;Separator;Thunar;ThunarNode1;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action SshDev]
Name=ssh dev
Exec=xfce4-terminal --tab --tab --title=node1 -x ssh-server node1

[Desktop Action SshS]
Name=ssh server
Exec=xfce4-terminal --title=server -x ssh-server

[Desktop Action SshNode1]
Name=ssh node1
Exec=xfce4-terminal --tab --title=node1 -x ssh-server node1

[Desktop Action SshLxd]
Name=ssh lxd
Exec=xfce4-terminal --tab --title=LXD -x ssh-server ssh-lxd

[Desktop Action Thunar]
Name=Thunar
Exec=thunar

[Desktop Action ThunarNode1]
Name=Thunar node1
Exec=thunar_newtabs /usr/local/bs sftp://root@node1/
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- mpv"
name=mpv
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;Celluloid;HandBrake;SubtitleEditor;MKVtoolnix;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Celluloid]
Name=Celluloid
Exec=celluloid

[Desktop Action MKVtoolnix]
Name=MKVtoolnix GUI
Exec=mkvtoolnix-gui

[Desktop Action SubtitleEditor]
Name=Subtitle editor
Exec=subtitleeditor

[Desktop Action HandBrake]
Name=HandBrake
Exec=ghb
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- gimp"
name=gimp
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="gThumb;Inkscape;Separator;XSane;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action gThumb]
Name=gThumb
Exec=gthumb %U

[Desktop Action Inkscape]
Name=Inkscape
Exec=inkscape %F

[Desktop Action XSane]
Name=XSane
Exec=xsane
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

_echot "------- libreoffice-startcenter"
name=libreoffice-startcenter
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;Archimate;Zotero;Galculator;QpdfView;Gcolor3;FontViewer;XfBurn;Brasero;"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Archimate]
Name=Archimate
Exec=archi

[Desktop Action Zotero]
Name=Zotero
Exec=zotero

[Desktop Action QpdfView]
Name=QpdfView
Exec=qpdfview

[Desktop Action Galculator]
Name=Galculator
Exec=galculator

[Desktop Action Gcolor3]
Name=Color Picker
Exec=gcolor3

[Desktop Action FontViewer]
Name=Font viewer
Exec=gtk2fontsel
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi
