#!/bin/bash

cd ${HOME}

########################  HOME SHARED

pth_to_init=/home/shared
echo "================ ${pth_to_init}"
pths="Books .config/gmusicbrowser .config/mpv .config/sayonara Desktop dev Documents Downloads .gse-radio Help"
pths+=" .perso Pictures repo .sublime-project Templates .themes .tmux .vscode-oss .vscode-oss-shared Zotero"
_echoa ${pths}
_askno "Give a new list or valid the subdirectories list above to link to ${pth_to_init} or 0 to skip"
[ "${_ANSWER}" ] && pths=${_ANSWER}

if [ "${_ANSWER}" != 0 ]; then
	errors=start
	while [ -n "${errors}" ]; do
		errors=
		for pth in ${pths}; do
			msg=
			pth_from=${pth}
			pth_to=${pth_to_init}/${pth}
			echo -n "${pth_from} "
			if [ -e ${pth_to} ]; then
				[ -h ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -f ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -d ${pth_from} ] && { rmdir ${pth_from} || msg="path is not empty"; }
				if [ -e ${pth_from} ]; then
					errors=y
					_echoe "- !!! failed !!! ${msg}"
				else
					ln -s ${pth_to} ${pth_from}
					echo "- ok"
				fi
			else
				_echoe "- *** skipped *** ${pth_to} is missing"
			fi
		done
		[ -n "${errors}" ] && _askno "Correct problem(s) and validate to continue"
	done
fi

########################  EXT SHARED

pth_to_init=/ext/shared
echo "================ ${pth_to_init}"
pths="android Archives Class Cnam Mooc Music Soft Videos"
_echoa ${pths}
_askno "Give a new list or valid the subdirectories list above to link to ${pth_to_init} or 0 to skip"
[ "${_ANSWER}" ] && pths=${_ANSWER}

if [ "${_ANSWER}" != 0 ]; then
	errors=start
	while [ -n "${errors}" ]; do
		errors=
		for pth in ${pths}; do
			pth_from=${pth}
			pth_to=${pth_to_init}/${pth}
			echo -n "${pth} "
			if [ -e ${pth_to} ]; then
				[ -h ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -f ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -d ${pth_from} ] && { rmdir ${pth_from} || msg="path is not empty"; }
				if [ -e ${pth_from} ]; then
					errors=y
					_echoe "- !!! failed !!! ${msg}"
				else
					ln -s ${pth_to} ${pth_from}
					echo "- ok"
				fi
			else
				_echoe "- *** skipped *** ${pth_to} is missing"
			fi
		done
		[ -n "${errors}" ] && _askno "Correct problem(s) and validate to continue"
	done
fi

########################  VMS SHARED

pth_to_init=/vms
echo "================ ${pth_to_init}"
pths="virt virtualbox vmware"
_echoa ${pths}
_askno "Give a new list or valid the subdirectories list above to link to ${pth_to_init} or 0 to skip"
[ "${_ANSWER}" ] && pths=${_ANSWER}

if [ "${_ANSWER}" != 0 ]; then
	errors=start
	while [ -n "${errors}" ]; do
		errors=
		for pth in ${pths}; do
			pth_from=${pth}
			pth_to=${pth_to_init}/${pth}
			echo -n "${pth} "
			if [ -e ${pth_to} ]; then
				[ -h ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -f ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
				[ -d ${pth_from} ] && { rmdir ${pth_from} || msg="path is not empty"; }
				if [ -e ${pth_from} ]; then
					errors=y
					_echoe "- !!! failed !!! ${msg}"
				else
					ln -s ${pth_to} ${pth_from}
					echo "- ok"
				fi
			else
				_echoe "- *** skipped *** ${pth_to} is missing"
			fi
		done
		[ -n "${errors}" ] && _askno "Correct problem(s) and validate to continue"
	done
fi

return 0
