#!/bin/bash

########################  REQUIRED

_echot "------- required files"
file_env=${S_PATH_SCRIPT}/conf/.sh_env
file_sh_aliases=${S_PATH_SCRIPT}/conf/.sh_aliases
file_sh_functions=${S_PATH_SCRIPT}/conf/.sh_functions
_require ${file_env} ${file_sh_aliases} ${file_sh_functions}

########################  MAIN

_echot "------- .sh_env"
file=/root/.sh_env
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_env} ${file}

_echot "------- .sh_aliases"
file=/root/.sh_aliases
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_sh_aliases} ${file}

_echot "-------  .sh_functions"
file=/root/.sh_functions
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_sh_functions} ${file}

_echot "------- common .*rc"
filetmp=/tmp/tmp.$(date +%s%N)
echo "
########################  PERSO

PS1='\[\033[01;31m\]\u@\h \[\033[1;37m\]\w\[\033[01;31m\]\$\[\033[00m\] '

# HISTORY
HISTSIZE=50000
HISTFILESIZE=50000

# source global variables
[ -f ~/.sh_env ] && . ~/.sh_env

# aliases
[ -f ~/.sh_aliases ] && . ~/.sh_aliases

# functions
[ -f ~/.sh_functions ] && . ~/.sh_functions" > ${filetmp}
for file in /root/.bashrc /root/.zshrc; do
	_keepcpts ${file}
	grep -sq '####  PERSO' ${file} || sudo sh -c "cat ${filetmp} >> ${file}"
done
_evalr rm ${filetmp}

_echot "------- .zshrc"
filetmp=/tmp/tmp.$(date +%s%N)
echo "
########################  SET OPTIONS

# split words in string with default delimiters ' '
setopt shwordsplit
# allows interactive comments in console
setopt interactivecomments
" > ${filetmp}
file=/root/.zshrc
grep -sq '####  SET OPTIONS' ${file} || sudo sh -c "cat ${filetmp} >> ${file}"
_evalr rm ${filetmp}

# force color
sudo sed -i '/^#force_color_prompt=/ s|#||' /root/.bashrc

_echot "------- .vimrc"
file=/root/.vimrc
file_from=${S_PATH_SCRIPT}/conf/.vimrc
_keepmvts ${file}
_evalr ln -s ${file_from} ${file}

