#!/bin/bash

########################  REQUIRED

_echot "------- required paths"
pth_conf=${_path_base}/perso/conf
_requirep ${pth_conf}

########################  DATA

anstmp=8
_askno "Give the size for global desktop font (${anstmp})"
font_size=${_ANSWER:-${anstmp}}

let anstmp=${font_size}+1
_askno "Give the size for global desktop font (${anstmp})"
font_interface_size=${_ANSWER:-${anstmp}}

anstmp=3600
_askno "Give the screensaver lock-delay inseconds (${anstmp})"
screen_lock_delay=${_ANSWER:-${anstmp}}

######################################################### GSETTINGS

_gnome_settings() {
	while read key value; do
		_eval "gsettings set $1 ${key} ${value}"
	done <<< "$2"
}

########################  DESKTOP

_echot "------- gsettings desktop"
pth=org.gnome.desktop.interface
options="font-name 'Ubuntu Sans ${font_interface_size}'
document-font-name 'Sans ${font_size}'
monospace-font-name 'Monospace ${font_size}'
clock-format '24h'
clock-show-weekday true"
_gnome_settings ${pth} "${options}"

########################  KEYBOARD

_echot "------- gsettings org.gnome.desktop.peripherals.keyboard"
pth=org.gnome.desktop.peripherals.keyboard
options="delay 'uint32 300'
numlock-state true
repeat-interval 'uint32 50'"
_gnome_settings ${pth} "${options}"

# screensaver
_eval "gsettings set org.gnome.desktop.screensaver lock-delay 'uint32 ${screen_lock_delay}'"
# sound
_eval "gsettings set org.gnome.desktop.sound event-sounds false"

########################  TERMINAL

_echot "------- dconf gnome-terminal"
_menu "Select the gnome-terminal profiles file to import" none $(cd ${pth_conf} && ls gnome-terminal-profiles*)
[ ${_ANSWER} != none ] && _eval "dconf load /org/gnome/terminal/legacy/profiles:/ < ${pth_conf}/${_ANSWER}"
# dconf dump /org/gnome/terminal/legacy/profiles:/ > ${pth_conf}/${_ANSWER}
# gsettings get org.gnome.Terminal.ProfilesList list
# gsettings get org.gnome.Terminal.ProfilesList default

########################  DOCK

_echot "------- gsettings dock"
pth=org.gnome.shell.extensions.dash-to-dock
options="always-center-icons true
background-opacity 0
dock-fixed false
dock-position 'BOTTOM'
scroll-action 'cycle-windows'
show-show-apps-button false
show-trash false
transparency-mode 'FIXED'"
_gnome_settings ${pth} "${options}"

########################  NAUTILUS

_echot "------- gsettings nautilus"
pth=org.gnome.nautilus.preferences
options="default-folder-viewer 'list-view'
show-create-link true
show-delete-permanently true
show-hidden-files true"
_gnome_settings ${pth} "${options}"

pth=org.gnome.nautilus.list-view
options="default-zoom-level 'small'
use-tree-view true"
_gnome_settings ${pth} "${options}"

pth=org.gnome.nautilus.compression
options="default-compression-format 'tar.xz'"
_gnome_settings ${pth} "${options}"

########################  MELD

_echot "------- gsettings meld"
pth=org.gnome.meld
options="custom-font 'monospace, ${font_size}'
highlight-current-line true
indent-width 4
prefer-dark-theme true
show-line-numbers true
show-overview-map true
style-scheme 'meld-dark-perso'
use-system-font true"
_gnome_settings ${pth} "${options}"

########################  WM

_echot "------- gsettings vim"
pth=org.gnome.desktop.wm.preferences
options="audible-bell false
titlebar-font 'Ubuntu Sans Bold 10'
visual-bell false"
_gnome_settings ${pth} "${options}"

########################  GTK

_echot "------- gsettings gtk"
pth=org.gtk.Settings.FileChooser
options="expand-folders true
show-hidden true"
_gnome_settings ${pth} "${options}"

########################  MUTTER

_echot "------- gsettings others"
_eval "gsettings set org.gnome.mutter center-new-windows true"
